myapp:
  name: myapp

  replicaCount: 1

  service:
    type: ClusterIP
    labels: {}
    annotations: {}
  containerPorts:
    http: 8080

  resources: {}

  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/backend-protocol: HTTP
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix
            backendName: myapp
            backendPort: 8080
    https: false
    tls: []

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 80

  affinity: {}
  tolerations: []
  nodeSelector: {}