name: Push Signed Image

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  AWS_DEFAULT_REGION: eu-central-1
  IMAGE_NAME: python-app
  IMAGE_TAG: latest
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com
  IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/python-app:latest

jobs:
  push-image:
    name: Push Signed Image to ECR
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download image artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Build
          name: docker-image
          path: .

      - name: Load Docker image
        run: |
          docker load -i image.tar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image
        run: |
          docker push "${{ env.IMAGE_URI }}"
